name: "CI"
on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - run: |
          sudo apt-get update
          sudo apt-get install -y valgrind
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: .nvmrc
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm moon check --all

  list-examples:
    runs-on: "ubuntu-latest"
    name: List examples
    outputs:
      examples: ${{ steps.list-examples.outputs.examples }}
    steps:
      - uses: "actions/checkout@v3"
      # list the directories in ./examples and output them to a github action workflow variables as a JSON array
      - run: |
          examples=$(find ./examples -maxdepth 1 -mindepth 1 -type d -printf '%f\n' | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "::set-output name=examples::$examples"
        id: list-examples

  node-versions:
    runs-on: "ubuntu-latest"
    name: "${{ matrix.example }} on Node ${{ matrix.node-version }}"
    needs: list-examples
    strategy:
      matrix:
        node-version: ["14", "16", "18", "20"]
        example: ${{ fromJson(needs.list-examples.outputs.examples) }}
        include:
          # tinybench does not support node 14
          - node-version: "14"
            pnpm-version: "7"
            skip-tinybench: true
        exclude:
          # esbuild-register does not work well with node 14
          - node-version: "14"
            example: with-typescript-cjs
          - node-version: "14"
            example: with-typescript-esm
          - node-version: "14"
            example: with-typescript-simple-esm
      fail-fast: false
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - run: |
          sudo apt-get update
          sudo apt-get install -y valgrind
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version || '' }}
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ matrix.node-version }}
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm moon run :build

      - name: Run benchmarks with tinybench-plugin
        if: matrix.skip-tinybench != true
        # use version from `main` branch to always test the latest version, in real projects, use a tag, like `@v1`
        uses: CodSpeedHQ/action@main
        with:
          run: pnpm --filter ${{ matrix.example }} bench-tinybench
        env:
          CODSPEED_SKIP_UPLOAD: true
          CODSPEED_DEBUG: true
      - name: Run benchmarks with benchmark.js-plugin
        # use version from `main` branch to always test the latest version, in real projects, use a tag, like `@v1`
        uses: CodSpeedHQ/action@main
        with:
          run: pnpm --filter ${{ matrix.example }} bench-benchmark-js
        env:
          CODSPEED_SKIP_UPLOAD: true
          CODSPEED_DEBUG: true
