name: "CI"
on:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - run: sudo apt-get install -y valgrind
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: .nvmrc
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm moon check --all

  codspeed:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - run: sudo apt-get install -y valgrind
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: .nvmrc
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm moon run :build

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v1
        with:
          run: pnpm moon run :bench
