name: "CI"
on:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - run: sudo apt-get install -y valgrind
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: .nvmrc
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm moon check --all

  codspeed:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - run: sudo apt-get install -y valgrind
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version-file: .nvmrc
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm moon run :build

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v1
        with:
          run: pnpm moon run :bench

  node-versions:
    runs-on: "ubuntu-latest"
    name: "Node ${{ matrix.node-version }}"
    strategy:
      matrix:
        node-version: ["14", "16", "18", "20"]
        include:
          - node-version: "14"
            pnpm-version: "7"
            skip-tinybench: true
      fail-fast: false
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0
      - run: sudo apt-get install -y valgrind
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version || '' }}
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ matrix.node-version }}
      - run: pnpm install --frozen-lockfile --prefer-offline
      - run: pnpm moon run :build

      - name: Run benchmarks with tinybench-plugin
        if: matrix.skip-tinybench != true
        uses: CodSpeedHQ/action@feat/node-script
        with:
          run: pnpm moon run tinybench-plugin:bench
        env:
          CODSPEED_SKIP_UPLOAD: true
      - name: Run benchmarks with benchmark.js-plugin
        uses: CodSpeedHQ/action@feat/node-script
        with:
          run: pnpm moon run benchmark.js-plugin:bench
        env:
          CODSPEED_SKIP_UPLOAD: true
